name: Update Algolia on schedule

on:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  update-algolia-on-schedule:
    runs-on: ubuntu-latest

    environment:
      name: update_algolia_on_schedule

    steps:
    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.115.4'

    - name: Checkout docs repo
      uses: actions/checkout@v3
      with:
        path: 'docs-repo'
        ref: 'main'

    - name: Print current docs repo branch/ref/commit
      working-directory: ./docs-repo
      run: |
        git status
        git log -1

    - name: Get linode-docs-theme version
      id: get-theme-version
      working-directory: ./docs-repo
      run: |
        LINODE_DOCS_THEME_VERSION=$(hugo mod graph | grep linode-docs-theme | cut -d '+' -f 1 | grep -o '[^-]*$')
        echo "VERSION=$LINODE_DOCS_THEME_VERSION" >> $GITHUB_OUTPUT

    - name: Set up SSH agent (linode-docs-theme repo deploy key)
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.LINODE_DOCS_THEME_DEPLOY_KEY_FOR_DOCS_DEPLOY_GHA }}

    - name: Checkout docs theme repo
      run: |
        git clone git@github.com:nmelehan/linode-docs-theme linode-docs-theme-repo

    - name: Check out theme repo commit from docs repo go.mod
      working-directory: ./linode-docs-theme-repo
      run: |
        git checkout ${{ steps.get-theme-version.outputs.VERSION }}

    - name: Print Linode Algolia admin tool version
      working-directory: ./linode-docs-theme-repo
      run: |
        cd scripts/linode_algolia_admin/
        go run main.go version

    - name: Update Algolia
      working-directory: ./linode-docs-theme-repo
      env:
        ALGOLIA_APP_ID: ${{ vars.ALGOLIA_APP_ID }}
        ALGOLIA_ADMIN_API_KEY: ${{ secrets.ALGOLIA_WRITE_KEY }}
      run: |
        cd scripts/linode_algolia_admin/

        # The refresh-merge-and-push sequence assumes that the linode-wp and linode-community indices already exist in the Algolia app
        go run main.go sequence refresh-merge-and-push